character = imread('./yong-small.png');
image(character) ;
[f, d] = vl_sift(single(rgb2gray(character)));
N = 24;
perm = randperm(size(f, 2)) ;
sel = perm(1:N) ;
h1 = vl_plotframe(f(:,sel)) ;
h2 = vl_plotframe(f(:,sel)) ;
set(h1,'color','k','linewidth',3) ;
set(h2,'color','y','linewidth',2) ;
